name: "A simple workflow"

on:
  pull_request:
    branches: '*'
  push:
    branches: '*'

jobs:
  test:
    name: "A simple job"
    runs-on: ubuntu-latest
    steps:
      - name: "Clone project repository"
        uses: actions/checkout@v3
      - name: "Execute a simple command"
        run: echo "Hello world"
